# Generated by Django 3.1 on 2021-04-23 07:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_catimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catimages',
            name='image',
            field=models.ImageField(upload_to=account.models.image_file_path),
        ),
    ]
