# Generated by Django 3.1 on 2021-04-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210423_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatImages',
        ),
    ]
