# Generated by Django 3.1 on 2021-04-23 07:24

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_catimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=account.models.image_file_path)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
