# Generated by Django 3.1 on 2021-04-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_catimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catimages',
            name='image',
        ),
    ]
